#   _____  __  __                 _         _____ _ _      _
# |  __ \|  \/  |     /\        | |       / ____| (_)    | |
# | |  | | \  / |    /  \  _   _| |_ ___ | |    | |_  ___| | _____ _ __
# | |  | | |\/| |   / /\ \| | | | __/ _ \| |    | | |/ __| |/ / _ \ '__|
# | |__| | |  | |  / ____ \ |_| | || (_) | |____| | | (__|   <  __/ |
# |_____/|_|  |_| /_/    \_\__,_|\__\___/ \_____|_|_|\___|_|\_\___|_|

#O Delay é definido em ticks, ou seja, delay de 1 segundo = 20. Para 20 hits por segundo, defina para 1. Recomendado: 3
Autoclick:
  ApenasMobs: true
  Delay: 3
  Distancia: 5

Mensagens:
  SemPermissao: '&cVocê não possui permissão para isso'
  Ativado: '&aAutoclick ativado com sucesso'
  Desativado: '&cAutoclick desativado com sucesso'

Dano:
  Itens:
    DIAMOND_SWORD: 7
    IRON_SWORD: 6
    GOLD_SWORD: 4
    STONE_SWORD: 5
    WOOD_SWORD: 4
  Encantamentos:
    DAMAGE_ALL: 1.25
  Pocoes:
    INCREASE_DAMAGE: 1.3
#O valor do encantamento trata-se do level 1. O valor é multiplicado a cada level. Exemplo: DAMAGE_ALL (Sharpness) com 2 de dano,
#somará mais 2 dano ao item caso esteja no level 1. Caso esteja no level 2, somará 4 de dano, level 3, somará 6 de dano e segue dessa forma.
#O dano da poção multiplica o dano da soma de item + encantamento